spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/bank
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

notification:
  enabledChannels:
    email: true
    sms: true